Add unit test logging and test name capability to m65
MEGA65/mega65-tools pull request #59
Opened 2021-05-23 11:42 UTC by steph72

Unit tests can now set their reported name, as well as log messages to the host computer's console.
An updated libc is needed to use this from C (see separate PR in mega65-libc)

2021-05-23 11:49 UTC, gardners requested changes
Please take a look at allowing VF011 mode to still co-exist with unit test mode, so that tests can be made that use a supplied D81 image.

2021-05-23 12:27 UTC, steph72 commented
vf011 requests are now also handled when unit testing
(trying to refactor some stuff out of the rather biblical main function ;-))

2021-05-23 22:36 UTC, gardners approved these changes
Looks good. You have tested the changes, I assume?

2021-05-23 23:32 UTC, steph72 commented
Yes, to the best of my knowledge everything still works.

2021-05-23 23:43 UTC, steph72 commented
@gardners That said, the "-d" option (f011 virtualization) never really worked for me on my, and it still freezes my devkit when I try to mount a disk image.
I just did a quick check and can confirm that it also didn't work before my changes, so I don't think I have broken anything that wasn't broken already. But maybe you can clarify the state of vf011 mode before I merge this...

2021-05-23 23:46 UTC, merged

2021-05-24 00:10 UTC, gardners commented
Check with Falk, as he is the chief user of it at the moment.
also note that I think -d requires -F to actually work, but I can't
remember for sure.

Paul.

On Mon, 24 May 2021 at 09:14, Stephan Kleinert ***@***.***>
wrote:

> @gardners <https://github.com/gardners> That said, the "-d" option (f011
> virtualization) never really worked for me on my, and it still freezes my
> devkit when I try to mount a disk image.
> I just did a quick check and can confirm that it also didn't work before
> my changes, so I don't think I have broken anything that wasn't broken
> already. But maybe you can clarify the state of vf011 mode before I merge
> this...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MEGA65/mega65-tools/pull/59#issuecomment-846644675>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFCOT6XESI6VBW3FAFROZDTPGHMJANCNFSM45LUCW3A>
> .
>